sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
  - rm -rf scss
cache:
  directories:
    - node_modules
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master